name:                ludicrous
version:             0.1.0.0
github:              "githubuser/project-cis552"
license:             BSD3
author:              "David and Saurabh"
maintainer:          "xudavid@seas.upenn.edu, surb@seas.upenn.edu"
copyright:           "2021"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Text editor for Lu
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/project-cis552#readme>

# You can add any libraries from stackage here (https://www.stackage.org/lts-18.8).
# if you need a library that is not available on stackage, you will need to add 
# an entry in stack.yaml.  
dependencies:
- base >= 4.14
- HUnit >= 1.6
- QuickCheck >= 2.14.2
- containers
- mtl
- pretty == 1.1.3.6
- brick
- cursor
- cursor-brick
- text
- path
- path-io
- vty
- microlens
- deepseq
- split
- parsec
- vector
- monad-memo

library:
  source-dirs: src
  default-extensions:
  - ScopedTypeVariables
  - TypeApplications
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - GeneralizedNewtypeDeriving
  - TupleSections
  - MultiParamTypeClasses
  - FlexibleInstances
  - FlexibleContexts
  - UndecidableInstances
  - NoMonomorphismRestriction
  - NoStarIsType


executables:
  ludicrous:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ludicrous
    default-extensions:
    - ScopedTypeVariables
    - TypeApplications
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - GeneralizedNewtypeDeriving
    - TupleSections
    - MultiParamTypeClasses
    - FlexibleInstances
    - FlexibleContexts
    - UndecidableInstances
    - NoMonomorphismRestriction
    - NoStarIsType


tests:
  ludicrous-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ludicrous
    default-extensions:
    - ScopedTypeVariables
    - TypeApplications
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - GeneralizedNewtypeDeriving
    - TupleSections
    - MultiParamTypeClasses
    - FlexibleInstances
    - FlexibleContexts
    - UndecidableInstances
    - NoMonomorphismRestriction
    - NoStarIsType